 
version: "3"

services:   
  mongo:
    container_name: mongo_dev 
    image: mongo
    ports:
      - 27017:27017
  api:
    container_name: users_api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ${PWD}:/app
    environment:
      - "USERS_DATABASE=mongodb://mongo/users"
    depends_on:
      - mongo